ACCSEC-19995 Move xcconfig variables
twilio/twilio-verify-ios pull request #121
Opened 2021-01-27 20:05 UTC by SergioFierro

## Jira Ticket
- ACCSEC- 19995

## Description
- Move config variables to a swift class

2021-01-27 22:08 UTC, AuthyApps commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

## Code coverage
### Total coverage: **`95.38%`**
File | Coverage
-----|-----
TwilioVerify/TwilioVerify/Sources/Domain/Factor/PushFactory.swift | **`99.33%`**
TwilioVerify/TwilioVerify/Sources/Networking/RequestHelper.swift | **`100.00%`**
> Powered by [Slather](https://github.com/SlatherOrg/slather)

<p align="right" data-meta="generated_by_UnitTests">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-01-27 22:27 UTC, AuthyApps commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

## Code coverage
### Total coverage: **`95.38%`**
File | Coverage
-----|-----
TwilioVerify/TwilioVerify/Sources/Domain/Factor/PushFactory.swift | **`99.33%`**
TwilioVerify/TwilioVerify/Sources/Networking/RequestHelper.swift | **`100.00%`**
> Powered by [Slather](https://github.com/SlatherOrg/slather)

<p align="right" data-meta="generated_by_UnitTests">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-01-28 00:13 UTC, yafuquen commented
Added commit message

2021-01-28 00:27 UTC, yafuquen requested changes

2021-01-28 00:27 UTC, yafuquen commented on TwilioVerify/Info.plist
> -	<key>CFBundleShortVersionString</key>
We should keep this to show the version in the SDK's general configuration

2021-01-28 15:53 UTC, AuthyApps commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

## Code coverage
### Total coverage: **`95.38%`**
File | Coverage
-----|-----
TwilioVerify/TwilioVerify/Sources/Domain/Factor/PushFactory.swift | **`99.33%`**
TwilioVerify/TwilioVerify/Sources/Networking/RequestHelper.swift | **`100.00%`**
> Powered by [Slather](https://github.com/SlatherOrg/slather)

<p align="right" data-meta="generated_by_UnitTests">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2021-01-28 16:27 UTC, yafuquen approved these changes

2021-01-28 23:02 UTC, Greshot approved these changes

2021-01-29 17:31 UTC, merged